apiVersion: v1
entries:
  busybox-chart:
  - apiVersion: v2
    appVersion: lastest
    created: "2021-10-29T06:22:33.7428221-06:00"
    description: A Helm Chart for running BusyBox
    digest: abec9361506478dfca73beb5c15a75b559a246db0b435914c9319bdb98823150
    home: https://www.busybox.net/
    icon: https://www.busybox.net/images/busybox1.png
    keywords:
    - busybox
    maintainers:
    - email: zimmermanc@gmail.com
      name: Chad Zimmerman
    name: busybox-chart
    type: application
    urls:
    - https://prymalinstynct.github.io/helm-charts/charts/busybox-chart-0.1.1.tgz
    version: 0.1.1
generated: "2021-10-29T06:22:33.7420977-06:00"
